---
sudo: true
language: ruby
cache: bundler
before_install:
- sudo apt-get install libzmq3-dev
rvm:
- jruby-1.7.24
script:
- bundle exec rspec spec
jdk: oraclejdk8
matrix:
  include:
  - rvm: jruby-9.1.10.0
    env: LOGSTASH_BRANCH=master
  - rvm: jruby-1.7.25
    env: LOGSTASH_BRANCH=5.x
  fast_finish: true
